### ISSUE TITLE
Hardcoded attributeNamePrefix value in xmlParserOptions

### ISSUE THREAD

**Issue by lwojcik** [extractus/feed-extractor#100]
Hi!

First and foremost, thanks for your work!

I've been using the library in my GitHub action and I tried to change `attributeNamePrefix` property in `xmlParserOptions` but it didn't work. I had a look at the code and noticed it's hardcoded and thus impossible to change:

https://github.com/extractus/feed-extractor/blob/4bdcdb1ba050a5564f1cbb570e692fb2311d2157/src/utils/xmlparser.js#L23

Is there any reasoning behind this decision I'm not aware of? Is it possible to make it modifiable via `xmlParserOptions` like the rest of the properties?

I can provide a pull request for this if you don't mind.

Thanks a lot!

**Comment by ndaidong** [comment]
@lwojcik nice to see your feedback. 

This fixed setting is just to simplify the normalization process, where we can access the attributes without caring prefix.

https://github.com/extractus/feed-extractor/blob/4bdcdb1ba050a5564f1cbb570e692fb2311d2157/src/utils/normalizer.js#L77-L97

I'm not sure in which case you have to change that setting?

**Comment by lwojcik** [comment]
In my use case I'd like to explore the possibility of passing an empty string as prefix or replacing it with a different string so that I can expose this feature to the end user in a safe way without resorting to dedicated helpers for specific properties.

If you're against refactoring the helper module, that's fine - but I feel the documentation could do a better job at informing me `attributeNamePrefix` can't be modified in `xmlParserOptions`. TypeScript typing doesn't do that either as you pass `any` for `xmlParserOptions` property.

**Comment by ndaidong** [comment]
@lwojcik you made me reconsider this issue. Since the library supports some customizations like `getExtraFeedFields` and `getExtraEntryFields`, it makes sense to allow any settings of xmlParserOptions to be changeable.
