### ISSUE TITLE
Empty description when content is wrapped in CDATA 

### ISSUE THREAD

**Issue by lwojcik** [extractus/feed-extractor#103]
Hi!

When I pass a feed that contains content wrapped in `CDATA` tags, normalized feed entry contains empty description.

Sample feeds:
- https://write.szkod.ovh/feed/
- https://writefreely.pl/mstankiewicz/feed/

For now I use a dirty workaround using `getExtraEntryFields` and some custom code to process HTML:

```js
getExtraEntryFields: (feedEntry) => {
	const cdataDescription = feedEntry.description.includes("<![CDATA[")
	  ? stripAndTruncateHTML(
	      feedEntry.description
	        .replaceAll("<![CDATA[", "")
	        .replaceAll("]]>'", ""),
	      siteConfig.maxPostLength
	    )
	  : "";

	return { cdataDescription };
}
```

Also - do you have a donation link or something? I'd love to buy you a coffee because this project ROCKS. ❤️

**Comment by ndaidong** [comment]
@lwojcik thank you for pointing out the issue.

I've investigated and found the cause. It relates to the function [buildDescription](https://github.com/extractus/feed-extractor/blob/main/src/utils/normalizer.js#L24), when we strip HTML tags from description text.

I'm going to fix it asap.

Regarding the donation, thank you for your compliment. I will add my Paypal link to README in the next update.

**Comment by lwojcik** [comment]
Works like charm. Thank you very much!

**Comment by ndaidong** [comment]
@lwojcik glad it worked for you, and thank you very much for the gift :moon_cake:
