### ISSUE TITLE
Medium feeds - no description tag, only content:encoded -> empty description

### ISSUE THREAD

**Issue by lwojcik** [extractus/feed-extractor#105]
Hi again!

I found another edge case and this time it's Medium feeds being naughty. They contain no `description` tag, only `content:encoded` with HTML content.

Example: https://medium.com/feed/@ameliakusiak

Traditionally, it can be worked around with `getExtraEntryFields`.

**Comment by ndaidong** [comment]
@lwojcik let's me see. I remember that I've worked with some RSS from Medium before.

**Comment by ndaidong** [comment]
@lwojcik I've found the cause. Medium feed applies RSS 2.0 standard but it does not use `description` tag, but `content:encoded` tag as same as Atom standard. This has been fixed with v7.0.3 by some tweeks.

**Comment by lwojcik** [comment]
Updated to v7.0.3, problem solved. Thank you very much!
