### ISSUE TITLE
feed.xml link field parsing error

### ISSUE THREAD

**Issue by jc955** [extractus/feed-extractor#111]
https://stephango.com/feed.xml

link field parsing error

![image](https://github.com/extractus/feed-extractor/assets/9528250/48a1720b-50e5-4010-a63e-cf128c4aefab)
![image](https://github.com/extractus/feed-extractor/assets/9528250/2b5712a2-323b-42c3-884f-19fda2e2acb4)

**Comment by ndaidong** [comment]
@0x1017 you can use [parserOptions](https://github.com/extractus/feed-extractor#parseroptions-optional) parameter to customize the output.

For example, if you turn off `normalization`, you can get the raw result, with full description:

```js
  const feed = await extract('https://www.historyinmemes.com/feed', {
    normalization: false,
  })
  console.log(feed)
```

If you still want to normalize feed data, let's use `getExtraEntryFields` to modify only description as below:

```js
  const feed = await extract(url, {
    getExtraEntryFields: (feedEntry) => {
      const { description } = feedEntry
      // you can do anything with the description here
      return {
        description,
      }
    },
  })
  console.log(feed)
```

**Comment by LavaCxx** [comment]
Even though I turned off `normalization`, the parsing of links still changed.
<img width="966" alt="image" src="https://github.com/extractus/feed-extractor/assets/48022591/69dd0e9b-37d3-43dd-9745-33291468aac3">

**Comment by LavaCxx** [comment]
After some research, I found that the problem is in the `fast-xml-parser`. Maybe the previous xml didn't support the `&` character, so this problem wasn't considered?
Anyway, if anyone else encounters this problem in the future, they can refer to the code.
```js
await extract(str, {
    normalization: false, xmlParserOptions: {
        tagValueProcessor: (tagName, tagValue) => {
            if (tagName === 'link') return tagValue.replace(/&/g, '&amp;')
            return ""
        }
    }
})
```
