### ISSUE TITLE
Now available as a Github Action

### ISSUE THREAD

**Issue by chriscarrollsmith** [extractus/feed-extractor#114]
Hi! Just wanted to alert you to the [Github Action wrapper](https://github.com/Promptly-Technologies-LLC/rss-fetch-action) I created for this tool, making it possible to use in continuous integration for Github Pages builds. Would love a link in the README!

**Comment by ndaidong** [comment]
@chriscarrollsmith great work! sorry for missing your notice. I will add a reference link in the next release.

**Comment by chriscarrollsmith** [comment]
Awesome! Currently you would have to add a separate step for each URL, but
I will open an issue to support fetching multiple URLs and resolve it later
this week.
