### ISSUE TITLE
Bug on heise.de

### ISSUE THREAD

**Issue by HubertHuckevoll** [extractus/feed-extractor#116]
Creates faulty object on https://www.heise.de/rss/heise-atom.xml
also on https://www.tagesschau.de/index~atom.xml

![image](https://github.com/extractus/feed-extractor/assets/8293309/cde10909-f54d-49ca-8201-7cf67bd0486b)

(description shows [object]...)

**Comment by ndaidong** [comment]
@HubertHuckevoll thank you for your report. This issue has been fixed with the last relsease 7.0.7
