### ISSUE TITLE
Would you accept a PR supporting CJS compatibility ?

### ISSUE THREAD

**Issue by olsonpm** [extractus/feed-extractor#118]
I totally understand if you'd prefer not to, just let me know either way.

Thanks for the tool :)

**Comment by ndaidong** [comment]
@olsonpm yes, with a deprecation warning like this one :)

https://vitejs.dev/guide/migration.html#deprecate-cjs-node-api

**Comment by ndaidong** [comment]
@olsonpm thank you, I've released v7.0.8 with your pr. 
If there is the relevant issue in the future, please help to resolve :)

**Comment by olsonpm** [comment]
feel free to ping me on any cjs issues

**Comment by olsonpm** [comment]
tested

```sh
$ mkdir test-cjs && cd test-cjs
$ npm init -f && npm i @extractus/feed-extractor
$ node -e 'require("@extractus/feed-extractor")'
The CJS build of @extractus/feed-extractor is deprecated. See https://github.com/extractus/feed-extractor#cjs-deprecated for details.
```
