### ISSUE TITLE
fetch error: cert invalid 

### ISSUE THREAD

**Issue by avelino** [extractus/feed-extractor#121]
```
Type:     FetchError
Message:  request to https://www.logseqtimes.com/rss/ failed, reason: Hostname/IP does not match certificate's altnames: Host: www.logseqtimes.com. is not in the cert's altnames: DNS:fallback.tls.fastly.net
```
ref: https://github.com/avelino/bots.clj.social/issues/103

---

there should be an option to bypass the certificate check

**Comment by ndaidong** [comment]
@avelino you can bypass the certificate check with this simple solution:

https://stackoverflow.com/a/52479399

However in this special case, logseqtimes.com does not have not only SSL certificate problem! When I ignore SSL checking, it redirects to a "Domain error" page.
