### ISSUE TITLE
not working but the sample site is

### ISSUE THREAD

**Issue by angelxmoreno** [extractus/feed-extractor#132]
This is how i use your code:
```ts
import { extract } from '@extractus/feed-extractor';

const sample1 = 'https://podcastfeeds.nbcnews.com/RPWEjhKq';

const parse = async () => {
    return extract(sample1);
}
```

I've tried 5 different urls and they all throw an error: `XML is invalid`.

the weird thing is that when I put that same url on https://extractor-demos.pages.dev/feed-extractor it seems to be able to parse just fine. is the demo page running a different version than v7.1.3 ?

**Comment by ndaidong** [comment]
@angelxmoreno how about your platform, Node.js and feed-extractor version?

Could you try the following steps to see if it works?

```sh
git clone https://github.com/extractus/feed-extractor.git
cd feed-extractor
npm install
npm run eval https://podcastfeeds.nbcnews.com/RPWEjhKq
```
In my machine it ran well:

![Screenshot from 2024-05-18 09-17-02](https://github.com/extractus/feed-extractor/assets/1809619/f0066d9e-059a-4e6d-b38c-0938442273fb)

**Comment by angelxmoreno** [comment]
thanks for the quick reply. Your questions led to me looking in the right place and I had an old version. update to 7.1.3 and all is good!
