### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by csimpi** [extractus/feed-extractor#71]
Hi, 
thx for this awesome library. 

Unfortunately, I can't fetch 90% of the RSS sources because of CORS issues.
Do you have any suggestions on how to solve it?

**Comment by ndaidong** [comment]
@csimpi where do you run it? nodejs or deno or browser?

**Comment by csimpi** [comment]
From browser, and I am wondering how to solve it now. Through an express gateway maybe?

**Comment by ndaidong** [comment]
@csimpi this is example for using this lib on browser. Please take a look:

https://github.com/extractus/feed-extractor/tree/main/examples/browser-feed-reader

**Comment by csimpi** [comment]
@ndaidong thank you, in the meantime, I did (almost) the same, and works, I really appreciate your help!
