### ISSUE TITLE
Content type octet-stream support

### ISSUE THREAD

**Issue by avelino** [extractus/feed-extractor#72]
Why is the content type checked?

I'm trying to consume a feed that returns octet-stream, can we support it?

https://github.com/extractus/feed-extractor/blob/8d65cd11fb85357901ca3f3bc0c6f9e97a82eec7/src/utils/retrieve.js#L33

ref: https://github.com/racket/racket-lang-org/issues/235

**Comment by ndaidong** [comment]
@avelino It just checks in a very loose way. And it uses this info to distinguish XML and JSON feed. Choosing octet-stream for RSS/ATOM is inappropriate MIME type. So let's wait and see if they change it. I think your request is reasonable.

**Comment by soegaard** [comment]
Which mime types are accepted?  
Perhaps `application/xml` and `text/xml` ?

**Comment by ndaidong** [comment]
@soegaard yes, it's just a quick check, therefore suitable for most common types.

### Standard

- `application/rss+xml`
- `application/atom+xml`
- `application/rdf+xml`

### Other:

- `application/xml`
- `text/xml`
- `text/html`
