### ISSUE TITLE
Add `id` property to entries

### ISSUE THREAD

**Issue by evert** [extractus/feed-extractor#73]
Nice library!

It would be helpful to have an 'id' property added to each entry. This allows an entry to be uniquely tracked, and ensures that if the URL of a feed item updates, it's still considered the same entry.

* JSON Feed has a required `id` property.
* RSS has `guid`, but it is optional. If it's not set the recommendation is generally to just use the URL instead as the unique identifier.
* Atom has the [id](https://www.rfc-editor.org/rfc/rfc4287#section-4.2.6) field for each entry, which is also required.

So it should be pretty easy to normalize this into an `id` field and make it non-optional in the type definition.

**Comment by ndaidong** [comment]
@evert agree with you, currently I'm using hash (md5 of url) to identify entry across the requests. We can add this field to extracted entries when they miss `id` or `guid`.

**Comment by evert** [comment]
Thank you!
