### ISSUE TITLE
IDE Type Error when adding optional FeedEntries like category

### ISSUE THREAD

**Issue by smc181002** [extractus/feed-extractor#83]
In the `index.d.ts` file https://github.com/extractus/feed-extractor/blob/b81646a23dbec4f9224cb1b19ea10f106d28d27f/index.d.ts#L3-L12

Since the feed entry allows for custom extra keys like `categories` and `enclosure`, Adding an optional parameter would stop the error that pops up in VSCode.

![image](https://user-images.githubusercontent.com/53662575/231860124-12d72555-20a9-4443-af70-611ba9035a31.png)

In my case, since I am using a string for tags (fetching medium RSS), adding the line like:
```typescript
interface FeedEntry{
   ...
   category?: Array<string>;
}
```

But I believe this would fail again if we have a custom object for categories like `text` and `domain` as mentioned in the examples on npm.

**Comment by ndaidong** [comment]
@smc181002 I'm not sure about how VSCode and TypeScript work in this case. Let's me investigate more. Or, could you try to fix and make a PR?
