### ISSUE TITLE
Issue with package types

### ISSUE THREAD

**Issue by M4RC3L05** [extractus/feed-extractor#85]
Hi,

Theres seems to be a problem with the package types, with something along the lines of: 
> There are types at '.../node_modules/@extractus/feed-extractor/index.d.ts', but this result could not be resolved when respecting package.json "exports". The '@extractus/feed-extractor' library may need to update its package.json or typings.

I was able to fix this locally by adding to the package.json `"types": "./index.d.ts",` on the `exports` section.
I can make a PR on this.

**Comment by ndaidong** [comment]
@M4RC3L05 yes, please help me. I'm not familiar with TS.

**Comment by ndaidong** [comment]
@M4RC3L05 I've released v6.2.2 with your pr. Please check if it resolves this issue. Thanks.
