### ISSUE TITLE
Add content:encoded  to FeedEntry

### ISSUE THREAD

**Issue by james-global-liquidity** [extractus/feed-extractor#93]
Thanks for a great tool. So far I've been using feed-extractor get feed items, and then passing each item's link to article-extractor to get the full article. However, I notice that in most of my feeds, the full text of the article is included in the RSS feed under the <content:encoded> tag. Is there already a way to get this data using feed-extractor so I wouldn't need to make a second call to article-extractor? It seems to me like it would be cool thing "encoded" were added as a property on FeedEntry, so that when it exists, we have access to it after parsing the feed. Is there a better way to do this?

**Comment by ndaidong** [comment]
@james-global-liquidity sorry for late reply. There is alreay a way to get that value. Could you share to me the RSS link so I can test it for you?
